package com.youou.aso.common.error;

public enum ErrorCode {
    OK,
    BAD_REQUEST,
    UNAUTHORIZED,
    FORBIDDEN,
    NOT_FOUND,
    CONFLICT,
    VALIDATION_ERROR,
    SYSTEM_ERROR,

    USERNAME_ALREADY_EXISTS,
    EMAIL_ALREADY_EXISTS,
    ACCOUNT_DISABLED,
    ACCOUNT_LOCKED,
    INVALID_USERNAME_OR_PASSWORD,
    PASSWORD_RESET_TOKEN_INVALID,
    PASSWORD_RESET_TOKEN_EXPIRED,
    PASSWORD_RESET_MAIL_UNAVAILABLE,
    FORCE_PASSWORD_CHANGE_REQUIRED,

    APP_NOT_FOUND_IN_STORE,
    APP_VERIFICATION_FAILED,
    APP_ALREADY_EXISTS,
    APP_NOT_VERIFIED,
    REGION_DISABLED,
    STORE_REGION_NOT_SUPPORTED,

    BALANCE_NOT_ENOUGH,
    WALLET_NOT_FOUND,
    WALLET_CONCURRENT_MODIFICATION,
    WALLET_TRANSACTION_TYPE_DISABLED,
    WALLET_TRANSACTION_TYPE_NOT_ALLOWED,
    WALLET_AMOUNT_INVALID,
    ORDER_ALREADY_DEDUCTED,
    ORDER_ALREADY_REFUNDED,

    PRICE_NOT_CONFIGURED,
    PRICE_DISABLED,
    PRICE_INVALID,

    ORDER_NOT_FOUND,
    ORDER_STATUS_INVALID,
    ORDER_ALREADY_EXECUTED,
    ORDER_ALREADY_COMPLETED,
    ORDER_DATE_INVALID,
    ORDER_QUANTITY_INVALID,
    EXECUTION_HOURS_INVALID,

    SPECIAL_AUDIT_NOT_FOUND,
    SPECIAL_AUDIT_STATUS_INVALID,
    SPECIAL_AUDIT_LOCKED,
    SPECIAL_AUDIT_NOT_APPROVED,
    SPECIAL_AUDIT_PRICE_REQUIRED,
    SPECIAL_AUDIT_PRICE_INVALID,
    SPECIAL_AUDIT_CANCEL_REASON_REQUIRED,

    CONFIG_NOT_FOUND,
    CONFIG_VALUE_INVALID,
    FILE_UPLOAD_FAILED,
    FILE_TYPE_NOT_ALLOWED,

    EXPORT_FAILED,
    EXPORT_TOO_MANY_ROWS
}
