INSERT INTO market_region (
    code, name_zh, name_en, enabled, supports_app_store, supports_google_play, supports_ipad_store, sort_order
) VALUES
    ('CN', '中国', 'China', TRUE, TRUE, TRUE, TRUE, 1),
    ('US', '美国', 'United States of America (USA)', TRUE, TRUE, TRUE, TRUE, 2),
    ('GB', '英国', 'Great Britain (United Kingdom; England)，UK', TRUE, TRUE, TRUE, TRUE, 3),
    ('FR', '法国', 'France', TRUE, TRUE, TRUE, TRUE, 4),
    ('DE', '德国', 'Germany', TRUE, TRUE, TRUE, TRUE, 5),
    ('JP', '日本', 'Japan，Japanese', TRUE, TRUE, TRUE, TRUE, 6),
    ('KR', '韩国', 'South Korea', TRUE, TRUE, TRUE, TRUE, 7),
    ('HK', '香港', 'Hong Kong', TRUE, TRUE, TRUE, TRUE, 8),
    ('TW', '台湾', 'Taiwan', TRUE, TRUE, TRUE, TRUE, 9),
    ('CA', '加拿大', 'Canada', TRUE, TRUE, TRUE, TRUE, 10),
    ('RU', '俄罗斯', 'Russian Federation|russia', TRUE, TRUE, TRUE, TRUE, 11),
    ('AU', '澳大利亚', 'Australia', TRUE, TRUE, TRUE, TRUE, 12),
    ('SG', '新加坡', 'Singapore', TRUE, TRUE, TRUE, TRUE, 13),
    ('VN', '越南', 'Vietnam', TRUE, TRUE, TRUE, TRUE, 14),
    ('TH', '泰国', 'Thailand', TRUE, TRUE, TRUE, TRUE, 15),
    ('SA', '沙特阿拉伯', 'Saudi Arabia', TRUE, TRUE, TRUE, TRUE, 16),
    ('MX', '墨西哥', 'Mexico', TRUE, TRUE, TRUE, TRUE, 17),
    ('IN', '印度', 'India', TRUE, TRUE, TRUE, TRUE, 18),
    ('ID', '印度尼西亚', 'Indonesia', TRUE, TRUE, TRUE, TRUE, 19),
    ('PH', '菲律宾', 'The Philippines', TRUE, TRUE, TRUE, TRUE, 20),
    ('AL', '阿尔巴尼亚', 'Albania', TRUE, TRUE, TRUE, TRUE, 21),
    ('DZ', '阿尔及利亚', 'Algeria', TRUE, TRUE, TRUE, TRUE, 22),
    ('AF', '阿富汗', 'Afghanistan', TRUE, TRUE, TRUE, TRUE, 23),
    ('AR', '阿根廷', 'Argentina', TRUE, TRUE, TRUE, TRUE, 24),
    ('IE', '爱尔兰', 'Ireland', TRUE, TRUE, TRUE, TRUE, 25),
    ('EG', '埃及', 'Egypt', TRUE, TRUE, TRUE, TRUE, 26),
    ('EE', '爱沙尼亚', 'Estonia', TRUE, TRUE, TRUE, TRUE, 27),
    ('AE', '阿拉伯联合酋长国', 'United Arab Emirates|阿联酋', TRUE, TRUE, TRUE, TRUE, 28),
    ('OM', '阿曼', 'Oman', TRUE, TRUE, TRUE, TRUE, 29),
    ('AO', '安哥拉', 'Angola', TRUE, TRUE, TRUE, TRUE, 30),
    ('AI', '安圭拉', 'Anguilla', TRUE, TRUE, TRUE, TRUE, 31),
    ('AG', '安提瓜和巴布达', 'Antigua & Barbuda', TRUE, TRUE, TRUE, TRUE, 32),
    ('AT', '奥地利', 'Austria', TRUE, TRUE, TRUE, TRUE, 33),
    ('MO', '澳门', 'Macao', TRUE, TRUE, TRUE, TRUE, 34),
    ('AZ', '阿塞拜疆', 'Azerbaijan', TRUE, TRUE, TRUE, TRUE, 35),
    ('BB', '巴巴多斯', 'Barbados', TRUE, TRUE, TRUE, TRUE, 36),
    ('PG', '巴布亚新几内亚', 'Papua New Guinea', TRUE, TRUE, TRUE, TRUE, 37),
    ('BS', '巴哈马', 'The Bahamas', TRUE, TRUE, TRUE, TRUE, 38),
    ('BY', '白俄罗斯', 'Belarus', TRUE, TRUE, TRUE, TRUE, 39),
    ('BM', '百慕大', 'Bermuda', TRUE, TRUE, TRUE, TRUE, 40),
    ('PK', '巴基斯坦', 'Pakistan', TRUE, TRUE, TRUE, TRUE, 41),
    ('PY', '巴拉圭', 'Paraguay', TRUE, TRUE, TRUE, TRUE, 42),
    ('BH', '巴林', 'Bahrain', TRUE, TRUE, TRUE, TRUE, 43),
    ('PA', '巴拿马', 'Panama', TRUE, TRUE, TRUE, TRUE, 44),
    ('BG', '保加利亚', 'Bulgaria', TRUE, TRUE, TRUE, TRUE, 45),
    ('BR', '巴西', 'Brazil', TRUE, TRUE, TRUE, TRUE, 46),
    ('BJ', '贝宁', 'Benin', TRUE, TRUE, TRUE, TRUE, 47),
    ('BE', '比利时', 'Belgium', TRUE, TRUE, TRUE, TRUE, 48),
    ('IS', '冰岛', 'Iceland', TRUE, TRUE, TRUE, TRUE, 49),
    ('BW', '博茨瓦纳', 'Botswana', TRUE, TRUE, TRUE, TRUE, 50),
    ('PL', '波兰', 'Poland', TRUE, TRUE, TRUE, TRUE, 51),
    ('BO', '玻利维亚', 'Bolivia', TRUE, TRUE, TRUE, TRUE, 52),
    ('BZ', '伯利兹', 'Belize', TRUE, TRUE, TRUE, TRUE, 53),
    ('BA', '波斯尼亚和黑塞哥维纳', 'Bosnia and Herzegovina', TRUE, TRUE, TRUE, TRUE, 54),
    ('BT', '不丹', 'Bhutan', TRUE, TRUE, TRUE, TRUE, 55),
    ('BF', '布基纳法索', 'Burkina', TRUE, TRUE, TRUE, TRUE, 56),
    ('DK', '丹麦', 'Denmark', TRUE, TRUE, TRUE, TRUE, 57),
    ('DO', '多米尼加', 'Dominican Republic', TRUE, TRUE, TRUE, TRUE, 58),
    ('DM', '多米尼克', 'Dominica', TRUE, TRUE, TRUE, TRUE, 59),
    ('EC', '厄瓜多尔', 'Ecuador', TRUE, TRUE, TRUE, TRUE, 60),
    ('FJ', '斐济', 'Fiji', TRUE, TRUE, TRUE, TRUE, 61),
    ('FI', '芬兰', 'Finland', TRUE, TRUE, TRUE, TRUE, 62),
    ('CV', '佛得角', 'Cape Verde', TRUE, TRUE, TRUE, TRUE, 63),
    ('GM', '冈比亚', 'Gambia', TRUE, TRUE, TRUE, TRUE, 64),
    ('CG', '刚果共和国', 'Republic of the Congo', TRUE, TRUE, TRUE, TRUE, 65),
    ('CD', '刚果民主共和国', 'Democratic Republic of the Congo', TRUE, TRUE, TRUE, TRUE, 66),
    ('GD', '格林纳达', 'Grenada', TRUE, TRUE, TRUE, TRUE, 67),
    ('GE', '格鲁吉亚', 'Georgia', TRUE, TRUE, TRUE, TRUE, 68),
    ('CO', '哥伦比亚', 'Colombia', TRUE, TRUE, TRUE, TRUE, 69),
    ('CR', '哥斯达黎加', 'Costa Rica', TRUE, TRUE, TRUE, TRUE, 70),
    ('GY', '圭亚那', 'Guyana', TRUE, TRUE, TRUE, TRUE, 71),
    ('KZ', '哈萨克斯坦', 'Kazakhstan', TRUE, TRUE, TRUE, TRUE, 72),
    ('ME', '黑山', 'Montenegro', TRUE, TRUE, TRUE, TRUE, 73),
    ('NL', '荷兰', 'Netherlands', TRUE, TRUE, TRUE, TRUE, 74),
    ('HN', '洪都拉斯', 'Honduras', TRUE, TRUE, TRUE, TRUE, 75),
    ('GH', '加纳', 'Ghana', TRUE, TRUE, TRUE, TRUE, 76),
    ('KH', '柬埔寨', 'Cambodia', TRUE, TRUE, TRUE, TRUE, 77),
    ('GA', '加蓬', 'Gabon', TRUE, TRUE, TRUE, TRUE, 78),
    ('CZ', '捷克', 'Czech Republic', TRUE, TRUE, TRUE, TRUE, 79),
    ('KG', '吉尔吉斯斯坦', 'Kyrgyzstan', TRUE, TRUE, TRUE, TRUE, 80),
    ('ZW', '津巴布韦', 'Zimbabwe', TRUE, TRUE, TRUE, TRUE, 81),
    ('GW', '几内亚比绍', 'Guinea-Bissau', TRUE, TRUE, TRUE, TRUE, 82),
    ('KY', '开曼群岛', 'Cayman Islands', TRUE, TRUE, TRUE, TRUE, 83),
    ('CM', '喀麦隆', 'Republic of Cameroon', TRUE, TRUE, TRUE, TRUE, 84),
    ('QA', '卡塔尔', 'Qatar', TRUE, TRUE, TRUE, TRUE, 85),
    ('HR', '克罗地亚', 'Croatia', TRUE, TRUE, TRUE, TRUE, 86),
    ('KE', '肯尼亚', 'Kenya', TRUE, TRUE, TRUE, TRUE, 87),
    ('XK', '科索沃', 'Kosovo', TRUE, TRUE, TRUE, TRUE, 88),
    ('CI', '科特迪瓦', 'Ivory Coast', TRUE, TRUE, TRUE, TRUE, 89),
    ('KW', '科威特', 'Kuwait', TRUE, TRUE, TRUE, TRUE, 90),
    ('LA', '老挝', 'Laos', TRUE, TRUE, TRUE, TRUE, 91),
    ('LV', '拉脱维亚', 'Latvia', TRUE, TRUE, TRUE, TRUE, 92),
    ('LB', '黎巴嫩', 'Lebanon', TRUE, TRUE, TRUE, TRUE, 93),
    ('LR', '利比里亚', 'Liberia', TRUE, TRUE, TRUE, TRUE, 94),
    ('LY', '利比亚', 'Libya', TRUE, TRUE, TRUE, TRUE, 95),
    ('LT', '立陶宛', 'Lithuania', TRUE, TRUE, TRUE, TRUE, 96),
    ('RO', '罗马尼亚', 'Romania', TRUE, TRUE, TRUE, TRUE, 97),
    ('LU', '卢森堡', 'Luxembourg', TRUE, TRUE, TRUE, TRUE, 98),
    ('RW', '卢旺达', 'Republic of Rwanda', TRUE, TRUE, TRUE, TRUE, 99),
    ('MG', '马达加斯加', 'Madagascar', TRUE, TRUE, TRUE, TRUE, 100),
    ('MV', '马尔代夫', 'Maldives', TRUE, TRUE, TRUE, TRUE, 101),
    ('MY', '马来西亚', 'Malaysia', TRUE, TRUE, TRUE, TRUE, 102),
    ('MW', '马拉维', 'Malawi', TRUE, TRUE, TRUE, TRUE, 103),
    ('ML', '马里', 'Mali', TRUE, TRUE, TRUE, TRUE, 104),
    ('MU', '毛里求斯', 'Mauritius', TRUE, TRUE, TRUE, TRUE, 105),
    ('MR', '毛里塔尼亚', 'Mauritania', TRUE, TRUE, TRUE, TRUE, 106),
    ('MK', '马其顿', 'Republic of Macedonia (FYROM)', TRUE, TRUE, TRUE, TRUE, 107),
    ('MT', '马其他', 'Malta', TRUE, TRUE, TRUE, TRUE, 108),
    ('MN', '蒙古', 'Mongolia', TRUE, TRUE, TRUE, TRUE, 109),
    ('MS', '蒙特塞拉特', 'Montserrat', TRUE, TRUE, TRUE, TRUE, 110),
    ('MM', '缅甸', 'Myanmar (Burma)', TRUE, TRUE, TRUE, TRUE, 111),
    ('FM', '密克罗尼西亚联邦', 'Federated States of Micronesia', TRUE, TRUE, TRUE, TRUE, 112),
    ('PE', '秘鲁', 'Peru', TRUE, TRUE, TRUE, TRUE, 113),
    ('MD', '摩尔多瓦', 'Moldova', TRUE, TRUE, TRUE, TRUE, 114),
    ('MA', '摩洛哥', 'Morocco', TRUE, TRUE, TRUE, TRUE, 115),
    ('MZ', '莫桑比克', 'Mozambique', TRUE, TRUE, TRUE, TRUE, 116),
    ('NA', '纳米比亚', 'Namibia', TRUE, TRUE, TRUE, TRUE, 117),
    ('ZA', '南非', 'South Africa', TRUE, TRUE, TRUE, TRUE, 118),
    ('NR', '瑙鲁', 'The Republic of Nauru', TRUE, TRUE, TRUE, TRUE, 119),
    ('NP', '尼泊尔', 'Nepal', TRUE, TRUE, TRUE, TRUE, 120),
    ('NI', '尼加拉瓜', 'Nicaragua', TRUE, TRUE, TRUE, TRUE, 121),
    ('NE', '尼日尔', 'Niger', TRUE, TRUE, TRUE, TRUE, 122),
    ('NG', '尼日利亚', 'Nigeria', TRUE, TRUE, TRUE, TRUE, 123),
    ('NO', '挪威', 'Norway', TRUE, TRUE, TRUE, TRUE, 124),
    ('PW', '帕劳', 'Palau', TRUE, TRUE, TRUE, TRUE, 125),
    ('PT', '葡萄牙', 'Portugal', TRUE, TRUE, TRUE, TRUE, 126),
    ('SE', '瑞典', 'Sweden', TRUE, TRUE, TRUE, TRUE, 127),
    ('CH', '瑞士', 'Switzerland', TRUE, TRUE, TRUE, TRUE, 128),
    ('SV', '萨尔瓦多', 'El Salvador', TRUE, TRUE, TRUE, TRUE, 129),
    ('RS', '塞尔维亚', 'Serbia', TRUE, TRUE, TRUE, TRUE, 130),
    ('SL', '塞拉利昂', 'Sierra Leone', TRUE, TRUE, TRUE, TRUE, 131),
    ('SN', '塞内加尔', 'Senegal', TRUE, TRUE, TRUE, TRUE, 132),
    ('CY', '塞浦路斯', 'Cyprus', TRUE, TRUE, TRUE, TRUE, 133),
    ('SC', '塞舌尔', 'Seychelles', TRUE, TRUE, TRUE, TRUE, 134),
    ('ST', '圣多美和普林西比', 'Sao Tome & Principe', TRUE, TRUE, TRUE, TRUE, 135),
    ('KN', '圣基茨和尼维斯', 'St. Kitts & Nevis', TRUE, TRUE, TRUE, TRUE, 136),
    ('LC', '圣卢西亚', 'St. Lucia', TRUE, TRUE, TRUE, TRUE, 137),
    ('VC', '圣文森特和格林纳丁斯', 'St. Vincent & the Grenadines', TRUE, TRUE, TRUE, TRUE, 138),
    ('LK', '斯里兰卡', 'Sri Lanka', TRUE, TRUE, TRUE, TRUE, 139),
    ('SK', '斯洛伐克', 'Slovakia', TRUE, TRUE, TRUE, TRUE, 140),
    ('SI', '斯洛文尼亚', 'Slovenia', TRUE, TRUE, TRUE, TRUE, 141),
    ('SZ', '斯威士兰', 'Swaziland', TRUE, TRUE, TRUE, TRUE, 142),
    ('SR', '苏里南', 'Suriname', TRUE, TRUE, TRUE, TRUE, 143),
    ('SB', '所罗门群岛', 'Solomon Islands', TRUE, TRUE, TRUE, TRUE, 144),
    ('TJ', '塔吉克斯坦', 'Tajikistan', TRUE, TRUE, TRUE, TRUE, 145),
    ('TO', '汤加', 'The Kingdom of Tonga', TRUE, TRUE, TRUE, TRUE, 146),
    ('TZ', '坦桑尼亚', 'Tanzania', TRUE, TRUE, TRUE, TRUE, 147),
    ('TC', '特克斯和凯科斯群岛', 'Turks & Caicos Islands', TRUE, TRUE, TRUE, TRUE, 148),
    ('TT', '特立尼达和多巴哥', 'Trinidad & Tobago', TRUE, TRUE, TRUE, TRUE, 149),
    ('TR', '土耳其', 'Turkey', TRUE, TRUE, TRUE, TRUE, 150),
    ('TM', '土库曼斯坦', 'Turkmenistan', TRUE, TRUE, TRUE, TRUE, 151),
    ('TN', '突尼斯', 'Tunisia', TRUE, TRUE, TRUE, TRUE, 152),
    ('VU', '瓦努阿图', 'Vanuatu', TRUE, TRUE, TRUE, TRUE, 153),
    ('GT', '危地马拉', 'Guatemala', TRUE, TRUE, TRUE, TRUE, 154),
    ('VE', '委内瑞拉', 'Venezuela', TRUE, TRUE, TRUE, TRUE, 155),
    ('BN', '文莱', 'Brunei', TRUE, TRUE, TRUE, TRUE, 156),
    ('UG', '乌干达', 'Uganda', TRUE, TRUE, TRUE, TRUE, 157),
    ('UA', '乌克兰', 'Ukraine', TRUE, TRUE, TRUE, TRUE, 158),
    ('UY', '乌拉圭', 'Uruguay', TRUE, TRUE, TRUE, TRUE, 159),
    ('UZ', '乌兹别克斯坦', 'Uzbekistan', TRUE, TRUE, TRUE, TRUE, 160),
    ('ES', '西班牙', 'Spain，Spanish', TRUE, TRUE, TRUE, TRUE, 161),
    ('GR', '希腊', 'Greece', TRUE, TRUE, TRUE, TRUE, 162),
    ('NZ', '新西兰', 'New Zealand', TRUE, TRUE, TRUE, TRUE, 163),
    ('HU', '匈牙利', 'Hungary', TRUE, TRUE, TRUE, TRUE, 164),
    ('JM', '牙买加', 'Jamaica', TRUE, TRUE, TRUE, TRUE, 165),
    ('AM', '亚美尼亚', 'Armenia', TRUE, TRUE, TRUE, TRUE, 166),
    ('YE', '也门', 'Yemen', TRUE, TRUE, TRUE, TRUE, 167),
    ('IT', '意大利', 'Italy', TRUE, TRUE, TRUE, TRUE, 168),
    ('IQ', '伊拉克', 'Iraq', TRUE, TRUE, TRUE, TRUE, 169),
    ('VG', '英属维尔京群岛', 'British Virgin Islands', TRUE, TRUE, TRUE, TRUE, 170),
    ('IL', '以色列', 'Israel', TRUE, TRUE, TRUE, TRUE, 171),
    ('JO', '约旦', 'Jordan', TRUE, TRUE, TRUE, TRUE, 172),
    ('ZM', '赞比亚', 'Zambia', TRUE, TRUE, TRUE, TRUE, 173),
    ('TD', '乍得', 'Chad', TRUE, TRUE, TRUE, TRUE, 174),
    ('CL', '智利', 'Chile', TRUE, TRUE, TRUE, TRUE, 175)
ON DUPLICATE KEY UPDATE
    name_zh = VALUES(name_zh),
    name_en = VALUES(name_en),
    sort_order = VALUES(sort_order);
