CREATE TEMPORARY TABLE order_module_description_defaults (
    order_type VARCHAR(64) PRIMARY KEY,
    old_zh VARCHAR(500), old_en VARCHAR(500), old_ru VARCHAR(500), old_pt VARCHAR(500), old_es VARCHAR(500),
    new_zh VARCHAR(500), new_en VARCHAR(500), new_ru VARCHAR(500), new_pt VARCHAR(500), new_es VARCHAR(500)
);

INSERT INTO order_module_description_defaults VALUES
('KEYWORD_INSTALL',
 '按关键词和地区配置安装任务，提升目标关键词下的自然表现。',
 'Configure installs by keyword and region to improve organic keyword performance.',
 'Настройте установки по ключевым словам и регионам для улучшения органических позиций.',
 'Configure instalações por palavra-chave e região para melhorar o desempenho orgânico.',
 'Configura instalaciones por palabra clave y región para mejorar el rendimiento orgánico.',
 '获得更多关键词安装，有助于提升目标关键词排名，让应用获得更多自然搜索流量。',
 'More keyword installs can improve target keyword rankings and bring your app more organic search traffic.',
 'Больше установок по ключевым словам помогает повысить позиции приложения и получить больше органического поискового трафика.',
 'Mais instalações por palavra-chave ajudam a melhorar o ranking e a gerar mais tráfego orgânico para a aplicação.',
 'Más instalaciones por palabra clave ayudan a mejorar el posicionamiento y atraer más tráfico orgánico a la aplicación.'),
('DOWNLOAD',
 '按日期、地区和下载量创建订单，增强应用市场基础热度。',
 'Create download campaigns by date and region to strengthen app market activity.',
 'Создавайте кампании загрузок по датам и регионам для роста активности приложения.',
 'Crie campanhas de downloads por data e região para reforçar a atividade da aplicação.',
 'Crea campañas de descargas por fecha y región para reforzar la actividad de la aplicación.',
 '持续增加应用下载量，能够增强市场热度与用户信任，吸引更多潜在用户关注和下载。',
 'Steady download growth builds market momentum and user confidence, attracting more people to discover and install your app.',
 'Стабильный рост загрузок усиливает интерес к приложению и доверие пользователей, привлекая новую аудиторию.',
 'O crescimento contínuo dos downloads aumenta a relevância e a confiança, atraindo mais utilizadores para a aplicação.',
 'El crecimiento constante de descargas aumenta el interés y la confianza, atrayendo a más usuarios a la aplicación.'),
('RATING',
 '配置五星和四星评分数量，提升应用的整体评分表现。',
 'Configure five-star and four-star ratings to improve the overall app rating.',
 'Настройте количество оценок 5 и 4 звезды для повышения общего рейтинга приложения.',
 'Configure classificações de cinco e quatro estrelas para melhorar a avaliação geral.',
 'Configura calificaciones de cinco y cuatro estrellas para mejorar la valoración general.',
 '更高、更稳定的应用评分能够增强用户信任，直接影响用户是否选择下载您的应用。',
 'A strong and stable app rating builds trust and directly influences whether users choose to download your app.',
 'Высокий и стабильный рейтинг укрепляет доверие и напрямую влияет на решение пользователя скачать приложение.',
 'Uma classificação elevada e estável reforça a confiança e influencia diretamente a decisão de descarregar a aplicação.',
 'Una calificación alta y estable genera confianza e influye directamente en la decisión de descargar la aplicación.'),
('REVIEW',
 '配置五星和四星评论数量，增加真实自然的用户反馈。',
 'Configure five-star and four-star reviews to build natural user feedback.',
 'Настройте отзывы на 5 и 4 звезды для формирования естественной обратной связи.',
 'Configure avaliações de cinco e quatro estrelas para criar feedback natural.',
 'Configura reseñas de cinco y cuatro estrellas para generar comentarios naturales.',
 '多数用户会在下载前查看评价；优质评价有助于建立口碑，提高应用的下载转化率。',
 'Most users read reviews before downloading; quality feedback strengthens credibility and improves download conversion.',
 'Большинство пользователей читают отзывы перед загрузкой; качественные отзывы укрепляют репутацию и повышают конверсию.',
 'A maioria dos utilizadores consulta avaliações antes de descarregar; boas avaliações reforçam a reputação e a conversão.',
 'La mayoría de los usuarios consulta reseñas antes de descargar; buenas reseñas mejoran la reputación y la conversión.'),
('RANK_GUARANTEE',
 '提交关键词排名目标，由管理员审核并确认执行方案。',
 'Submit a keyword ranking target for admin review and execution planning.',
 'Укажите целевую позицию ключевого слова для проверки и планирования администратором.',
 'Defina uma posição-alvo da palavra-chave para revisão e planeamento do administrador.',
 'Define una posición objetivo de palabra clave para revisión y planificación.',
 '为目标关键词提供持续的排名维护，帮助应用稳定占据更有价值的搜索位置。',
 'Maintain valuable positions for target keywords so your app can retain stronger, more consistent search visibility.',
 'Поддерживайте выгодные позиции по целевым ключевым словам и сохраняйте стабильную видимость приложения в поиске.',
 'Mantenha posições valiosas para palavras-chave alvo e preserve uma presença mais estável nos resultados de pesquisa.',
 'Mantén posiciones valiosas para palabras clave objetivo y conserva una visibilidad más estable en las búsquedas.'),
('CHART_RANK_GUARANTEE',
 '填写榜单目标与排名要求，由管理员审核并确认执行方案。',
 'Set a chart target and ranking requirement for admin review and planning.',
 'Укажите цель и позицию в чарте для проверки и планирования администратором.',
 'Defina o objetivo e a posição no ranking para revisão e planeamento.',
 'Define el objetivo y la posición en el ranking para revisión y planificación.',
 '通过榜单排名维护提升应用在分类榜或总榜中的曝光，持续获得更多用户关注。',
 'Maintain category or overall chart positions to increase app exposure and attract sustained user attention.',
 'Удерживайте позиции в категории или общем чарте, повышая заметность приложения и интерес пользователей.',
 'Mantenha posições no ranking geral ou da categoria para aumentar a exposição e o interesse dos utilizadores.',
 'Mantén posiciones en rankings generales o de categoría para aumentar la exposición y el interés de los usuarios.'),
('KEYWORD_COVERAGE',
 '扩展关键词覆盖范围，提升应用在更多搜索词下的可见度。',
 'Expand keyword coverage to increase visibility across more search terms.',
 'Расширьте охват ключевых слов и видимость приложения в поиске.',
 'Amplie a cobertura de palavras-chave e a visibilidade nas pesquisas.',
 'Amplía la cobertura de palabras clave y la visibilidad en las búsquedas.',
 '扩展更多潜力关键词的搜索覆盖，让应用被更多目标用户发现并获得持续自然流量。',
 'Expand visibility across more relevant keywords so target users can discover your app through more searches.',
 'Расширяйте охват релевантных ключевых слов, чтобы больше целевых пользователей находили приложение через поиск.',
 'Expanda a visibilidade para mais palavras-chave relevantes e permita que mais utilizadores encontrem a aplicação.',
 'Amplía la visibilidad a más palabras clave relevantes para que más usuarios objetivo descubran la aplicación.');

UPDATE order_module_config c
JOIN order_module_description_defaults d ON d.order_type = c.order_type
SET c.module_description = d.new_zh,
    c.module_description_en = d.new_en,
    c.module_description_ru = d.new_ru,
    c.module_description_pt = d.new_pt,
    c.module_description_es = d.new_es
WHERE (c.module_description = '' OR c.module_description = d.old_zh)
  AND (c.module_description_en = '' OR c.module_description_en = d.old_en)
  AND (c.module_description_ru = '' OR c.module_description_ru = d.old_ru)
  AND (c.module_description_pt = '' OR c.module_description_pt = d.old_pt)
  AND (c.module_description_es = '' OR c.module_description_es = d.old_es);

DROP TEMPORARY TABLE order_module_description_defaults;
