const en = {
  startMode: "Start mode", startImmediately: "Start now", startScheduled: "Schedule a start", immediateStartHint: "The server sets the order time when you submit. The order still follows the normal confirmation and execution process.", 
  rechargeTime: "Recharge time", transactionTime: "Transaction time", changeAmount: "Amount changed ($)", balanceAfterRecharge: "Balance after recharge", remark: "Remarks", 
  leave: 'Leave without saving',
  filters: 'More filters', collapse: 'Collapse', switchService: 'Change service', regionSearch: 'Search country or code',
  changedOnly: 'Modified only', priceScope: 'Prices', allPrices: 'All regions', overrides: 'Custom prices', defaults: 'Default prices',
  unsaved: 'Unsaved changes', saved: 'No unsaved changes', systemTime: 'System time (UTC+8)',
  billingQuantity: 'Total = daily quantity × days × regional unit price.', billingReview: 'Total = number of reviews × regional unit price for each star rating.',
  billingQuote: 'Submit requirements → administrator quote → confirm and pay.', billingAdmin: 'Total = unit price × days for each item.',
  unitPrecision: 'Unit prices: 4 decimal places. Totals: 2 decimal places.',
  discard: 'There are unsaved price changes. Leave this page?', filterCount: '{count} filters selected',
  required: 'This field is required.'
}
export const visualMessages = {
  'en-US': en,
  'zh-CN': {
  startMode: "开始方式", startImmediately: "立即开始", startScheduled: "预约开始", immediateStartHint: "提交时由服务器确定订单时间，之后仍按正常流程确认和执行。", 
  rechargeTime: "充值时间", transactionTime: "发生时间", changeAmount: "变动金额（$）", balanceAfterRecharge: "充值后余额", remark: "备注",  leave:'放弃修改并离开', filters:'更多筛选',collapse:'收起',switchService:'切换服务',regionSearch:'搜索国家名称或代码',changedOnly:'仅看已修改',priceScope:'价格范围',allPrices:'全部地区',overrides:'自定义价格',defaults:'默认价格',unsaved:'有未保存的修改',saved:'当前修改已保存',systemTime:'系统时间（UTC+8）',billingQuantity:'总费用 = 每日数量 × 天数 × 地区单价。',billingReview:'总费用 = 各星级评价条数 × 对应地区单价。',billingQuote:'提交需求 → 管理员报价 → 确认并支付。',billingAdmin:'总费用按每项单价 × 天数汇总。',unitPrecision:'单价保留 4 位小数，结算总额保留 2 位小数。',discard:'价格配置有未保存的修改，确定离开？',filterCount:'已选 {count} 项筛选',required:'请填写此项。' },
  'ru-RU': {
  startMode: "Способ начала", startImmediately: "Начать сейчас", startScheduled: "Запланировать", immediateStartHint: "Сервер задаст время заказа при отправке. Подтверждение и выполнение проходят в обычном порядке.", 
  rechargeTime: "Время пополнения", transactionTime: "Время операции", changeAmount: "Сумма изменения ($)", balanceAfterRecharge: "Баланс после пополнения", remark: "Примечания",  leave:'Выйти без сохранения', filters:'Больше фильтров',collapse:'Свернуть',switchService:'Сменить услугу',regionSearch:'Поиск страны или кода',changedOnly:'Только изменения',priceScope:'Цены',allPrices:'Все регионы',overrides:'Особые цены',defaults:'Стандартные цены',unsaved:'Есть несохранённые изменения',saved:'Изменения сохранены',systemTime:'Системное время (UTC+8)',billingQuantity:'Итого = количество в день × дни × региональная цена.',billingReview:'Итого = число отзывов × региональная цена для каждой оценки.',billingQuote:'Требования → предложение администратора → подтверждение и оплата.',billingAdmin:'Итого: сумма цены × дней по каждой позиции.',unitPrecision:'Цена за единицу: 4 знака. Итог: 2 знака.',discard:'Есть несохранённые цены. Покинуть страницу?',filterCount:'Выбрано фильтров: {count}',required:'Обязательное поле.' },
  'pt-PT': {
  startMode: "Modo de início", startImmediately: "Iniciar agora", startScheduled: "Agendar início", immediateStartHint: "O servidor define a hora ao enviar o pedido. A confirmação e a execução seguem o processo habitual.", 
  rechargeTime: "Data da recarga", transactionTime: "Data da transação", changeAmount: "Valor da alteração ($)", balanceAfterRecharge: "Saldo após recarga", remark: "Observações",  leave:'Sair sem guardar', filters:'Mais filtros',collapse:'Recolher',switchService:'Alterar serviço',regionSearch:'Pesquisar país ou código',changedOnly:'Apenas alterados',priceScope:'Preços',allPrices:'Todas as regiões',overrides:'Preços personalizados',defaults:'Preços predefinidos',unsaved:'Alterações por guardar',saved:'Alterações guardadas',systemTime:'Hora do sistema (UTC+8)',billingQuantity:'Total = quantidade diária × dias × preço regional.',billingReview:'Total = número de comentários × preço regional por classificação.',billingQuote:'Requisitos → orçamento do administrador → confirmação e pagamento.',billingAdmin:'Total: soma do preço × dias de cada item.',unitPrecision:'Preço unitário: 4 casas decimais. Total: 2.',discard:'Existem preços por guardar. Sair da página?',filterCount:'{count} filtros selecionados',required:'Campo obrigatório.' },
  'es-ES': {
  startMode: "Modo de inicio", startImmediately: "Iniciar ahora", startScheduled: "Programar inicio", immediateStartHint: "El servidor fija la hora al enviar el pedido. La confirmación y la ejecución siguen el proceso habitual.", 
  rechargeTime: "Fecha de recarga", transactionTime: "Fecha de transacción", changeAmount: "Importe del cambio ($)", balanceAfterRecharge: "Saldo tras la recarga", remark: "Observaciones",  leave:'Salir sin guardar', filters:'Más filtros',collapse:'Contraer',switchService:'Cambiar servicio',regionSearch:'Buscar país o código',changedOnly:'Solo modificados',priceScope:'Precios',allPrices:'Todas las regiones',overrides:'Precios personalizados',defaults:'Precios predeterminados',unsaved:'Cambios sin guardar',saved:'Cambios guardados',systemTime:'Hora del sistema (UTC+8)',billingQuantity:'Total = cantidad diaria × días × precio regional.',billingReview:'Total = número de reseñas × precio regional por valoración.',billingQuote:'Requisitos → presupuesto del administrador → confirmación y pago.',billingAdmin:'Total: suma del precio × días por elemento.',unitPrecision:'Precio unitario: 4 decimales. Total: 2.',discard:'Hay precios sin guardar. ¿Salir de la página?',filterCount:'{count} filtros seleccionados',required:'Campo obligatorio.' }
}
